### PR TITLE
Automated dependency upgrades

### PR DESCRIPTION
**Pull request by hc-github-team-secure-vault-ecosystem**
Full log: https://github.com/hashicorp/vault-plugin-secrets-azure/actions/runs/10704206017

  IMPROVEMENTS:
* Updated dependencies:
   * `github.com/Azure/azure-sdk-for-go/sdk/azcore` v1.11.1 -> v1.14.0
   * `github.com/Azure/azure-sdk-for-go/sdk/azidentity` v1.6.0 -> v1.7.0
   * `github.com/go-test/deep` v1.1.0 -> v1.1.1
   * `github.com/hashicorp/vault/api` v1.13.0 -> v1.14.0
   * `github.com/hashicorp/vault/sdk` v0.12.0 -> v0.13.0
   * `github.com/microsoftgraph/msgraph-sdk-go` v1.42.0 -> v1.47.0
   * `github.com/microsoftgraph/msgraph-sdk-go-core` v1.1.0 -> v1.2.1

### CODE REVIEW

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/27321

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/27321

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/27321

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/27321

**Comment by Zlaticanin** [comment]
@dependabot rebase

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/27321

**Review by Zlaticanin — APPROVED** [review]

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/27321

**Pull request merged**
